version: 0.2
phases:
  pre_build:
    commands:
    - echo Entering pre_build phase...
    - ls -lrt
  build:
    commands:
    - echo Entering build phase...
    - echo Build started on `date`
    - mvn clean prepare-package war:exploded
    - ls -lrt
    - ls -lrt target/
  post_build:
    commands:
    - echo Entering post_build phase...
    - echo Build completed on `date`i
    - ls -lrt
    - mv target/deploy ./
artifacts:
  files:
  - deploy/**/*